### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by Dyrnwyrm** [Anderware/Combat-Tracker-Extensions#1]
First of all thanks for the module is awesome but after i enabled it on my world im seeing a lot of these errors on the console
![Captura](https://github.com/Anderware/Combat-Tracker-Extensions/assets/129613553/a9650754-1ef8-4bc0-ae3a-1cefe1b3955b)
![Captura2](https://github.com/Anderware/Combat-Tracker-Extensions/assets/129613553/f3c8522b-d85d-4bc5-8908-b43e322e1554)

by just moving around/starting the world

**Comment by Anderware** [comment]
Thank you for trying out the module!
Yeah, I have seen those and fixed them in the upcoming next version

**Comment by Anderware** [comment]
Fixed in v1.1
