### ISSUE TITLE
The ui is shifted to the left when using the plutonium

### ISSUE THREAD

**Issue by Memorize-Remix** [Anderware/Combat-Tracker-Extensions#4]
When I use this module, I notice that when I enable plutonium, its ui interface is offset directly to the far left.
I'm using plutonium version 1.74.2, FVTT version 11.315, and DND5e 2.4.1.
![image](https://github.com/Anderware/Combat-Tracker-Extensions/assets/62300045/e342e55f-6228-483c-a216-a8c5a8d76e96)

**Comment by Anderware** [comment]
Thank you for trying out Combat-Tracker-Extensions.
Unfortunately, the module you are referring to is a non-sanctioned module that has legal issues attached to it. 
As such, I can not install it, and therefor am I not able to troubleshoot this problem. 
Sorry for the inconvenience.
